In [2]:
100 % 9

1

In [4]:
import numpy as np

In [3]:
w = np.array([0.0000000e+00, 4.8938165e-03, 0.0000000e+00, 8.7765692e-04, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.7618630e-03
, 1.6832582e-03, 7.4703936e-03, 0.0000000e+00, 7.4703936e-03, 7.4703936e-03
, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.3179331e-03, 7.4703936e-03
, 2.9956133e-03, 0.0000000e+00, 7.4703936e-03, 7.3291087e-03, 3.5115716e-03
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 7.4703936e-03, 7.4703936e-03
, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 1.2145840e-03, 7.4703936e-03, 0.0000000e+00, 7.4703936e-03
, 2.1565885e-03, 7.4703936e-03, 0.0000000e+00, 4.3547632e-05, 7.4703936e-03
, 7.4703936e-03, 6.5353974e-03, 0.0000000e+00, 7.4703936e-03, 6.1868443e-03
, 1.1176964e-03, 1.0204569e-03, 0.0000000e+00, 0.0000000e+00, 6.0442705e-03
, 0.0000000e+00, 0.0000000e+00, 8.0280693e-04, 0.0000000e+00, 1.9087032e-03
, 0.0000000e+00, 6.3525261e-03, 4.4938023e-03, 3.9483900e-03, 7.4703936e-03
, 5.9221368e-03, 0.0000000e+00, 0.0000000e+00, 6.2213890e-04, 0.0000000e+00
, 0.0000000e+00, 2.6297575e-04, 0.0000000e+00, 0.0000000e+00, 8.1655203e-04
, 7.4703936e-03, 0.0000000e+00, 7.4703936e-03, 8.6984003e-04, 0.0000000e+00
, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 2.5834891e-04, 0.0000000e+00, 2.9411339e-03, 0.0000000e+00, 7.4703936e-03
, 2.2310710e-03, 0.0000000e+00, 0.0000000e+00, 2.1224816e-03, 7.4703936e-03
, 0.0000000e+00, 6.0695065e-03, 0.0000000e+00, 6.0583069e-04, 2.8750894e-03
, 0.0000000e+00, 1.9780369e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 2.3988030e-04, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00
, 2.9863543e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.3933139e-03
, 0.0000000e+00, 0.0000000e+00, 4.7388733e-03, 3.9530362e-04, 0.0000000e+00
, 0.0000000e+00, 6.9509414e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 2.1942717e-03, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 8.0433313e-04
, 0.0000000e+00, 3.2551100e-03, 0.0000000e+00, 4.3625464e-03, 5.5313655e-03
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.2889595e-03, 4.7132289e-03
, 0.0000000e+00, 0.0000000e+00, 1.7744756e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 6.9402419e-03, 0.0000000e+00, 0.0000000e+00
, 5.8709946e-03, 0.0000000e+00, 0.0000000e+00, 3.6568404e-03, 4.2767494e-04
, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00, 1.3602239e-03
, 1.9455735e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 9.4163284e-04, 0.0000000e+00, 7.4703936e-03, 2.6130874e-03, 3.3749335e-03
, 5.5340109e-03, 0.0000000e+00, 2.0487616e-03, 0.0000000e+00, 0.0000000e+00
, 2.6964562e-03, 0.0000000e+00, 7.4703936e-03, 4.5705214e-03, 0.0000000e+00
, 2.5629213e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 1.0129805e-03, 0.0000000e+00, 7.4703936e-03
, 7.4703936e-03, 0.0000000e+00, 4.7229012e-03, 0.0000000e+00, 4.7881049e-03
, 3.1138491e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 4.6182508e-03, 2.4753204e-03, 6.5828860e-03, 0.0000000e+00, 0.0000000e+00
, 3.2796750e-03, 7.4703936e-03, 4.5326138e-03, 5.1447661e-03, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 5.3527164e-03, 3.8246065e-03, 7.4703936e-03
, 2.8737553e-04, 0.0000000e+00, 2.0652718e-03, 4.2785006e-03, 0.0000000e+00
, 0.0000000e+00, 2.8083182e-03, 3.1632562e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 7.4703936e-03, 6.5262616e-04, 0.0000000e+00, 7.1670781e-03
, 0.0000000e+00, 6.6892020e-03, 0.0000000e+00, 4.8372471e-03, 2.8457711e-03
, 3.2443053e-03, 1.7977068e-03, 0.0000000e+00, 6.5706377e-03, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 1.1115350e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00, 1.5040332e-03
, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 2.3448837e-03
, 4.1892636e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 1.8480527e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.8628918e-04
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 5.3159840e-04, 3.3169768e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0355497e-03, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 2.8584502e-03, 0.0000000e+00, 1.5799776e-03
, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 1.9332288e-03, 7.4703936e-03
, 0.0000000e+00, 2.9776087e-03, 3.4339741e-04, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 5.4902271e-03, 7.0907217e-03, 3.7049663e-03
, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03
, 0.0000000e+00, 0.0000000e+00, 1.1903328e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.2288037e-03
, 1.6813939e-03, 4.0870388e-03, 0.0000000e+00, 0.0000000e+00, 2.1578639e-03
, 7.4703936e-03, 7.4703936e-03, 7.4703936e-03, 5.4036938e-03, 7.4703936e-03
, 2.5762159e-03, 0.0000000e+00, 0.0000000e+00, 2.3548437e-04, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 4.6167816e-03, 7.1598105e-03, 9.8635466e-04
, 7.4703936e-03, 6.3732909e-03, 0.0000000e+00, 7.4703936e-03, 7.4426564e-03
, 0.0000000e+00, 1.5770402e-03, 1.0473626e-03, 7.4703936e-03, 7.4703936e-03
, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00, 5.5238511e-03, 0.0000000e+00
, 3.4482655e-04, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.6001166e-03
, 0.0000000e+00, 7.4601490e-03, 6.8846252e-03, 7.4703936e-03, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5278030e-03, 7.4703936e-03
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 4.3465458e-03, 0.0000000e+00
, 0.0000000e+00, 7.4703936e-03, 1.1565140e-03, 4.2180931e-03, 0.0000000e+00
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03, 0.0000000e+00
, 0.0000000e+00, 1.6992745e-03, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 7.4703936e-03, 3.2229519e-03, 2.0039042e-03, 5.0023720e-03
, 9.5165154e-04, 0.0000000e+00, 7.4703936e-03, 1.9348166e-03, 0.0000000e+00
, 0.0000000e+00, 2.7913929e-04, 0.0000000e+00, 5.5955851e-04, 0.0000000e+00
, 0.0000000e+00, 4.1299802e-03, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03
, 3.6614584e-03, 0.0000000e+00, 7.4703936e-03, 7.4703936e-03, 7.4703936e-03
, 0.0000000e+00, 1.4270861e-03, 0.0000000e+00, 7.4703936e-03, 4.9302541e-03
, 0.0000000e+00, 7.4703936e-03, 5.2567391e-04, 7.4703936e-03, 0.0000000e+00
, 7.4703936e-03, 0.0000000e+00, 2.7698276e-03, 6.6344719e-03, 3.4318666e-03
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00
, 2.6167657e-03, 6.2847012e-03, 7.4703936e-03, 0.0000000e+00, 0.0000000e+00
, 3.6013990e-03, 0.0000000e+00, 0.0000000e+00, 7.7594537e-04, 2.6999912e-03
, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.4587382e-03
, 3.2619280e-03, 3.2786251e-04, 0.0000000e+00, 0.0000000e+00, 6.7857695e-03
, 2.0532683e-03, 4.0840833e-03, 0.0000000e+00, 0.0000000e+00, 1.4553624e-03
, 0.0000000e+00, 6.4486340e-03, 1.6522647e-03, 0.0000000e+00, 0.0000000e+00
, 0.0000000e+00, 6.2393921e-04, 1.8885005e-03, 5.7401680e-03, 0.0000000e+00
, 7.4703936e-03, 4.7017122e-03, 3.4956314e-04, 0.0000000e+00, 3.8625116e-03
, 0.0000000e+00, 4.6131453e-03, 0.0000000e+00, 0.0000000e+00, 7.4703936e-03])

# Sharpe - https://medium.com/the-innovation/portfolio-analysis-basics-volatility-sharpe-ratio-d7521d79ba0

In [1]:
import pandas as pd
import numpy as np
def daily_returns(prices):
    # cur_price / prev_price - 1.0 = daily_returns
    res = (prices/prices.shift(1) - 1.0)[1:]
    res.columns = ['return']

    return res
def brownian_prices(start, end,
                    mu=0.0001, sigma=0.01, s0=100.0):

    bdates = pd.bdate_range(start, end)
    size = len(bdates)

    np.random.seed(1)
    wt = np.random.standard_normal(size)
    # GBM process
    st = s0 * np.cumprod(
        np.exp(mu - (sigma * sigma / 2.0)
        + sigma * wt))

    return pd.DataFrame(data={'date': bdates,
                              'price': st}).set_index('date')

In [2]:
start = '20100101'
end = '20200101'
returns1 = daily_returns(brownian_prices(start,
                                         end,
                                         mu=0.002,
                                         sigma=0.01,
                                         s0=100.0))

returns2 = daily_returns(brownian_prices(start,
                                         end,
                                         mu=0.002,
                                         sigma=0.02,
                                         s0=100.0))

returns3 = daily_returns(brownian_prices(start,
                                         end,
                                         mu=0.0022,
                                         sigma=0.05,
                                         s0=100.0))

returns4 = daily_returns(brownian_prices(start,
                                         end,
                                         mu=0.0054,
                                         sigma=0.1,
                                         s0=100.0))

In [4]:
returns1

return
date                
2010-01-04 -0.004159
2010-01-05 -0.003326
2010-01-06 -0.008741
2010-01-07  0.010660
2010-01-08 -0.020845
...              ...
2019-12-26  0.002696
2019-12-27 -0.008546
2019-12-30  0.001946
2019-12-31  0.006036
2020-01-01  0.013667

[2608 rows x 1 columns]

In [5]:
print(np.nanstd(returns1))
print(np.nanstd(returns2))
print(np.nanstd(returns3))
print(np.nanstd(returns4))

0.01005330534613989
0.020109030209555907
0.050316302807302545
0.10117352761398334


In [193]:
def sharpe(returns, risk_free=0.1):
    adj_returns = returns - risk_free
    return (np.nanmean(adj_returns) * np.sqrt(252)) \
           / np.nanstd(adj_returns)

In [194]:
print(sharpe(returns1))
print(sharpe(returns2))
print(sharpe(returns3))
print(sharpe(returns4))

-154.4273669320855
-77.04650243719105
-30.538064133447165
-14.522850543390465


In [28]:
def sortino(returns, risk_free=0):
    adj_returns = returns - risk_free
    
    sqr_downside = np.square(np.clip(adj_returns, np.NINF, 0))
    drisk = np.sqrt(np.nanmean(sqr_downside) * 252)

    if drisk == 0:
        return np.nan

    return (np.nanmean(adj_returns) * np.sqrt(252))  / drisk

In [27]:
print(sortino(returns1))
print(sortino(returns2))
print(sortino(returns3))
print(sortino(returns4))

0.3703086929584153
0.18661284367980077
0.09636439957056862
0.11485292733996215


In [29]:
print(sortino(returns1))
print(sortino(returns2))
print(sortino(returns3))
print(sortino(returns4))

0.3703086929584153
0.18661284367980077
0.09636439957056862
0.11485292733996215


In [ ]:
    def get_sharpe(self):
        
        # If the standard deviation is 0 then this means we a risk free investment - very unlikley
        # However in the early stages of a portfolio this could be true so we set the sharp ratio to 0
        # which infers a return equal to the risk free rate
        
        if np.std(self.portfolio_returns_history) == 0:
            sharpe = 0
        
        else:
            
            # Risk free interest rate is the minimum of the risk free rate param and the risk free rate apportioned across lookback days
            sharpe = (np.mean(self.adj_returns) \
                      * np.sqrt(self.effective_lookback)) \
                      / np.std(self.adj_returns)
        
        return sharpe
    
    def get_sortino(self):
        
        # Downside risk
        sqr_downside = np.square(np.clip(self.adj_returns, np.NINF, 0))
        downside_risk = np.sqrt(np.nanmean(sqr_downside) * self.effective_lookback)
        
        if downside_risk == 0:
            sortino = 0
        else:
            sortino = (np.nanmean(self.adj_returns) * np.sqrt(self.effective_lookback))
            
        return sortino

In [30]:
rfr =0.5

In [31]:
lb = 252

In [32]:
day = 252/2


In [34]:
day/lb * rfr

0.25

In [83]:
def sharpe(returns, risk_free=0):
    adj_returns = returns - risk_free
    return (np.nanmean(adj_returns) * np.sqrt(252)) \
           / np.nanstd(adj_returns)

In [81]:
print(sharpe(returns1))
print(sharpe(returns2))
print(sharpe(returns3))
print(sharpe(returns4))

3.4760023561335767
1.8956827450854112
1.0113681195196318
1.1675264166331212


In [66]:
def sharpe2(returns, risk_free=0, lb=252, day=252):
    adj_returns = returns[-min(day,lb):] - ((min(day,lb)/lb) * risk_free)
    return np.nanmean(adj_returns) / np.nanstd(adj_returns)

In [84]:
print(sharpe(returns1,0.5))
print(sharpe(returns2,0.5))
print(sharpe(returns3,0.5))
print(sharpe(returns4,0.5))

-786.0408440849619
-392.815243166297
-156.73579314531435
-77.28435838348481


In [74]:
print(sharpe2(returns1,0.5))
print(sharpe2(returns2,0.5))
print(sharpe2(returns3,0.5))
print(sharpe2(returns4,0.5))

-50.0297746038411
-25.015236338855665
-9.997460630441553
-4.943012105718515


In [52]:
returns1.tail(), returns1[-1:]

(              return
 date                
 2019-12-26  0.002696
 2019-12-27 -0.008546
 2019-12-30  0.001946
 2019-12-31  0.006036
 2020-01-01  0.013667,
               return
 date                
 2020-01-01  0.013667)

In [76]:
import quantstats as qs

In [96]:
126/252 * 0.5

0.25

In [164]:
qs.stats.sharpe(returns = returns1, rf = 0.5)

return    0.933131
dtype: float64

In [165]:
qs.stats.sharpe(returns = returns1, rf = 0.0)


return    3.475336
dtype: float64

In [108]:
qs.stats.sharpe(returns = returns1, rf = 0.5, periods=126, annualize=True, trading_year_days = 252),

(return   -1.613167
 dtype: float64,)

In [129]:
r = np.array(returns1['return'])

In [130]:
r

array([-0.00415889, -0.00332617, -0.00874126, ...,  0.00194576,
        0.00603574,  0.01366713])

In [159]:
ep.sharpe_ratio(returns1,0.5)

array([-785.89013162])

In [116]:
ep.sharpe_ratio(returns = returns1, risk_free = 0.5, annualization=252 )

array([-785.89013162])

In [176]:
def qsharpe(returns, rf=0., periods=252, trading_year_days=252):
    
    rf = returns - np.power(1 + rf, 1. / periods) - 1.
    
    adj_returns = returns - rf
    
    sharpe = np.mean(adj_returns) / adj_returns.std() * np.sqrt(trading_year_days)
    
    return sharpe
    

In [177]:
qsharpe(returns = r, rf = 0.5)

<ipython-input-176-7ecd0be38ff9>:7: RuntimeWarning: divide by zero encountered in double_scalars
  sharpe = np.mean(adj_returns) / adj_returns.std() * np.sqrt(trading_year_days)


inf

In [187]:
r1 = qs.utils._prepare_returns(returns1, 0.5, 252)

In [203]:
    def get_sharpe(r): 
                                                  
        adj_returns =  r -  0.5                                    
        sharpe  = (adj_returns.mean() / r.std()) #* np.sqrt(252)
        
        return sharpe

In [204]:
get_sharpe(returns1['return'])

-49.50642490693479

In [189]:
qs.stats.sharpe(returns = returns1, rf = 0.5)

return    0.933131
dtype: float64

In [200]:
returns1['return'].mean()

0.0022013478064479217

In [201]:
returns1['return'].std()

0.010055233298088988

In [205]:
def sharpe_ratio(return_series, N, rf):
    mean = return_series.mean() * N -rf
    sigma = return_series.std() * np.sqrt(N)
    return mean / sigma

In [207]:
sharpe_ratio(returns1['return'], 252, 0.5)

0.34293323192533404

In [257]:
import ffn

In [209]:
cumulative_ret=r.cumprod()

In [212]:
import matplotlib.pyplot as plt
fig = plt.figure()
#ax1 = fig.add_axes([0.1,0.1,0.8,0.8])
ax1.plot(cumulative_ret)
ax1.set_xlabel('Date')
ax1.set_ylabel("Cumulative Returns")
ax1.set_title("Portfolio Cumulative Returns")
plt.show();

<Figure size 432x288 with 0 Axes>

In [218]:
len(cumulative_ret)

2608

In [221]:
cumulative_ret[1]

1.3833196046540004e-05

In [228]:
x = np.array([0.78662558,1.18723672, 1.53037466, 1.41413817, 0., 1.43687504 ,1.1500508,  1.6526738,  1.48494461, 1.11052821, 1.6424263])

In [229]:
x.cumprod()

array([0.78662558, 0.93391077, 1.42923338, 2.02113348, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [252]:
x = np.array([1,0.78662558,1.18723672, 1.53037466, 1.41413817, 0.68399145, 1.43687504 ,1.1500508,  1.6526738,  1.48494461, 1.11052821, 1.6424263])

In [253]:
x.cumprod()

array([ 1.        ,  0.78662558,  0.93391077,  1.42923338,  2.02113348,
        1.38243802,  1.98639068,  2.2844502 ,  3.77545099,  5.60633559,
        6.22599383, 10.22573601])

In [256]:
x.prod(), x.prod().squeeze()

(10.225736010362425, 10.225736010362425)

In [232]:
(x+1).cumprod()

array([2.00000000e+00, 3.57325116e+00, 7.81554615e+00, 1.97762599e+01,
       4.77426239e+01, 8.03981705e+01, 1.95920295e+02, 4.21238587e+02,
       1.11740856e+03, 2.77669839e+03, 5.86030028e+03, 1.54854116e+04])

In [248]:
 r[-1]-r[-2]/r[-2]

-0.9863328732882632

In [239]:
r

array([-0.00415889, -0.00332617, -0.00874126, ...,  0.00194576,
        0.00603574,  0.01366713])

In [240]:
6/3 *100

200.0

In [249]:
(2-1)/1 *100

100.0

In [244]:
(1.7 -1.8) * 100

-1699.9999999999986

In [250]:
(10-8) / 8

0.25

In [251]:
(10/8) -1

0.25

In [265]:
x=np.array([1,2,-3,-4,5,6,-7,8,9,17,-18,-12,-4,-6,1,2,4,-9])

In [270]:
x[-2:]

array([ 4, -9])

In [263]:
y=x[x <0]

In [264]:
y

array([-3, -4, -7])

In [274]:
np.square(y).sum()

74

In [275]:
np.square(y).sum() / 18

4.111111111111111

In [278]:
np.sqrt(np.square(y).sum() / 18)

2.0275875100994063

In [279]:
((50000 + 25000) / 50000) ** (1/4) - 1

0.10668191970032148

In [281]:
(75000 / 50000) ** (1/4) - 1

0.10668191970032148

In [282]:
x

array([  1,   2,  -3,  -4,   5,   6,  -7,   8,   9,  17, -18, -12,  -4,
        -6,   1,   2,   4,  -9])

In [283]:
x[-1]

-9

In [ ]:
d = x